In [2]:
import numpy as np

In [4]:
np.array(range(0,100))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [10]:
o = np.array(range(0,100))

o.reshape(100,1) / 2.0


array([[  0. ],
       [  0.5],
       [  1. ],
       [  1.5],
       [  2. ],
       [  2.5],
       [  3. ],
       [  3.5],
       [  4. ],
       [  4.5],
       [  5. ],
       [  5.5],
       [  6. ],
       [  6.5],
       [  7. ],
       [  7.5],
       [  8. ],
       [  8.5],
       [  9. ],
       [  9.5],
       [ 10. ],
       [ 10.5],
       [ 11. ],
       [ 11.5],
       [ 12. ],
       [ 12.5],
       [ 13. ],
       [ 13.5],
       [ 14. ],
       [ 14.5],
       [ 15. ],
       [ 15.5],
       [ 16. ],
       [ 16.5],
       [ 17. ],
       [ 17.5],
       [ 18. ],
       [ 18.5],
       [ 19. ],
       [ 19.5],
       [ 20. ],
       [ 20.5],
       [ 21. ],
       [ 21.5],
       [ 22. ],
       [ 22.5],
       [ 23. ],
       [ 23.5],
       [ 24. ],
       [ 24.5],
       [ 25. ],
       [ 25.5],
       [ 26. ],
       [ 26.5],
       [ 27. ],
       [ 27.5],
       [ 28. ],
       [ 28.5],
       [ 29. ],
       [ 29.5],
       [ 30. ],
       [ 30.5],
       [

In [16]:
np.random.choice(10, 6).reshape(2, 3)

array([[8, 0, 6],
       [3, 6, 3]])

In [17]:
z = np.zeros(5, 5)

TypeError: data type not understood

In [18]:
np.identity(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [20]:
def one():
    '''
    INPUT: NONE
    OUTPUT: A numpy row vector of 100 sequential numbers starting at zero and ending at 99. (matrix)

    Create a row vector with numpy (1 x 100).

    Example:
    >>>
    >>> answer = one()
    >>> print answer
    >>> [[ 0  1  2  3  4 ... 99 ]]
    '''
    return np.array(range(0,100))

M = one().reshape(10, 10)

M

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [24]:
M[:, 0:3]

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32],
       [40, 41, 42],
       [50, 51, 52],
       [60, 61, 62],
       [70, 71, 72],
       [80, 81, 82],
       [90, 91, 92]])

In [25]:
M[-2:]

array([[80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [34]:
V = np.array([np.array(range(0, 10))])

In [35]:
V + 0.5


array([[ 0.5,  1.5,  2.5,  3.5,  4.5,  5.5,  6.5,  7.5,  8.5,  9.5]])

In [36]:
V * -2

array([[  0,  -2,  -4,  -6,  -8, -10, -12, -14, -16, -18]])

In [40]:
B = np.array([0.5]* 10)
B + V


array([[ 0.5,  1.5,  2.5,  3.5,  4.5,  5.5,  6.5,  7.5,  8.5,  9.5]])

In [46]:
def thirteen():
    '''
    Create column vector with 3 ints, called as column_vector.
    Create a row vector with 3 ints, called as row_vector.
    Create 3 x 3 square matrix called and square_matrix:
    Return as column_vector, row_vector, square_matrix (IN THAT ORDER)
    '''
    return np.array([5,6,7]).reshape(3, 1), np.array([5,6,7]), np.random.choice(10, 9).reshape(3, 3)

thirteen()

(array([[5],
        [6],
        [7]]), array([5, 6, 7]), array([[1, 1, 6],
        [8, 9, 0],
        [2, 5, 5]]))

c, r, ar = thirteen()

c * r

In [50]:
c, r, m = thirteen()

m * r

array([[30, 24, 56],
       [30, 54,  7],
       [15,  0, 63]])

In [52]:
r * c

array([[25, 30, 35],
       [30, 36, 42],
       [35, 42, 49]])

In [57]:
A = np.array(range(0, 6)).reshape(3, 2)
A

B = np.array(range(0, 12)).reshape(4, 3)
B

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [60]:
np.dot(A, B)

ValueError: shapes (3,2) and (4,3) not aligned: 2 (dim 1) != 4 (dim 0)

In [61]:
np.dot(B, A)

array([[10, 13],
       [28, 40],
       [46, 67],
       [64, 94]])

In [67]:
rand_matrix = np.random.choice(30, 18).reshape(3, 6)
rand_matrix.reshape(6, 3) * rand_matrix

ValueError: operands could not be broadcast together with shapes (6,3) (3,6) 

In [68]:
a = np.random.choice(30, 12).reshape(6, 2)

In [69]:
a

array([[21, 22],
       [ 1, 23],
       [ 4, 20],
       [19, 27],
       [22, 20],
       [ 8, 18]])

In [70]:
a * a

array([[441, 484],
       [  1, 529],
       [ 16, 400],
       [361, 729],
       [484, 400],
       [ 64, 324]])

In [74]:
A = np.array([ [1], [2], [3], [4] ])
B = np.array([[ 100.0,  200.0,   300.0]])

A + B

array([[ 101.,  201.,  301.],
       [ 102.,  202.,  302.],
       [ 103.,  203.,  303.],
       [ 104.,  204.,  304.]])

In [85]:

m = np.linspace(0, 99, num=100, endpoint=True).reshape(10,10)

In [89]:
np.mean(m, axis=1)

array([  4.5,  14.5,  24.5,  34.5,  44.5,  54.5,  64.5,  74.5,  84.5,  94.5])

In [83]:
np.column_stack(m)

array([[  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,
         11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,
         22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,
         33.,  34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,
         44.,  45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,
         55.,  56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,
         66.,  67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,
         77.,  78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,
         88.,  89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,
         99.]])

In [88]:
np.column_stack(m)

array([[  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90.],
       [  1.,  11.,  21.,  31.,  41.,  51.,  61.,  71.,  81.,  91.],
       [  2.,  12.,  22.,  32.,  42.,  52.,  62.,  72.,  82.,  92.],
       [  3.,  13.,  23.,  33.,  43.,  53.,  63.,  73.,  83.,  93.],
       [  4.,  14.,  24.,  34.,  44.,  54.,  64.,  74.,  84.,  94.],
       [  5.,  15.,  25.,  35.,  45.,  55.,  65.,  75.,  85.,  95.],
       [  6.,  16.,  26.,  36.,  46.,  56.,  66.,  76.,  86.,  96.],
       [  7.,  17.,  27.,  37.,  47.,  57.,  67.,  77.,  87.,  97.],
       [  8.,  18.,  28.,  38.,  48.,  58.,  68.,  78.,  88.,  98.],
       [  9.,  19.,  29.,  39.,  49.,  59.,  69.,  79.,  89.,  99.]])